### ISSUE TITLE
malware?

### ISSUE THREAD

**Issue by LinuxUserGD** [slydelv/FRST-Download-Update#1]
https://github.com/slydelv/FRST-Download-Update/releases/download/Release/FRST-Download-Update.exe
https://www.virustotal.com/gui/file/0315a9db027456b069fd0b6171cab61c567e45f931e3dde7db2fe2b3316c2335

**Comment by slydelv** [comment]
No, FRST is used for removing malware. 
You can check the source of FRST-Download-Update.exe at https://github.com/slydelv/FRST-Download-Update
It's written in Autoit, the same as FRST.

**Comment by LinuxUserGD** [comment]
Ok, thanks for clarification
